---
title: "Flexdashboard with opencpu back-end"
output: 
  flexdashboard::flex_dashboard:
    theme: cerulean
    orientation: rows
    # logo: testlogo.png
    # social: [ "twitter", "facebook"]
    # navbar:
    #   - { title: "About", href: "http://data-laborer.eu", align: right }
    # source_code: "https://github.com/YvesCR/flexocpu"
---

```{r, echo=FALSE}
htmltools::tags$script(src = "//code.jquery.com/jquery-1.11.1.min.js")
htmltools::tags$script(src = "//cdn.opencpu.org/opencpu-0.4.js")
htmltools::tags$script(src = "../js/opensilex.js")
htmltools::tags$script(src = "../js/app.js")
```


```{r setup, include=FALSE}
# devtools::install_github("Rstudio/flexdashboard")
library(flexdashboard)
```

Demo
===================================== 

Row {data-height=200}
-------------------------------------

### Definition {data-width=800}

Test for a dashboard with opencpu.

Loading a page is slow due to the size of the web page loaded: so far 1.4 Mb.
Most of the size is due to the flexdashboard interface (multiple pages & tab adjustment).

There is a trade off between the complexity of the page (mobile compatible or not, multiple pages, etc.) and the size of the page.

```{r, echo=TRUE}
print(2+2)
```

### Maps

```{r}
htmltools::tags$input(type="integer", class="form-control", id="myid", value="1", style = "width: 90%")
htmltools::tags$button("Update dashboard!", type="submit", id="idsubmit", class="btn btn-default")
```

